### PR TITLE
Update application.dart

### PR DESCRIPTION
**Pull request by KimJon12**
Hello, I am a Korean user. I am using your software so well that I am translating it into Korean and uploading it, even though it is not enough.

### CODE REVIEW

**Comment by kirill-21** [comment]
Thank you, it will be great if you also translate website files

**Comment by kirill-21** [comment]
Btw. you can join our discord, I'll give you some role there and you can give me your ExLoader Nickname/email so that I disable ads for you there)

**Comment by kirill-21** [comment]
image
Is this human-made translation?

**Comment by KimJon12** [comment]
> image Is this human-made translation? image
> 
> It's quality is really bad, i don't think users will use it


I partially translated it with Google Translate and edited it separately to fit the sentence. I couldn't check some of them. Let's review it again.

**Comment by KimJon12** [comment]
> image

I checked that part. So we are modifying the translation results to make them look more natural. It may be slightly different from the literal translation, but there is no problem in using it. We promise to continuously update and modify it so that it can be viewed well by Koreans.

**Pull request closed without merging**
